### ISSUE TITLE
Strange problems with new release of FocusWriter (May 2nd)

### ISSUE THREAD

**Issue by TailaBlu** [flathub/org.gottcode.FocusWriter#14]
I recently updated to the newest FocusWriter release on Windows 11. In doing this I do get a cool new dark mode but... This seems to carry into the actual input field, and I can't seem to get rid of it. What's stranger is, when I switch to a light theme, the block simply turns white. I have a lot of different themes of a lot of different colors to set a lot of different moods. I've tried everything I can think of thus far. I've gone full screen. I've closed and opened it again. I changed my overall computer theme. And yet the block persists. Could someone please help me?
![1716098498666571](https://github.com/flathub/org.gottcode.FocusWriter/assets/59271278/32051208-d135-4c4c-b65c-d33081946c94)

**Comment by gottcode** [comment]
This has been fixed in git (and only applies to Windows, not the Flatpak version), and will be fixed in the next release (version 1.8.8). For now you can workaround it by telling Qt to ignore dark mode support in Windows by adding `-platform windows:darkmode=0` to the program arguments.
