### ISSUE TITLE
NovProg & FocusWriter ... Wondering ... or am i missing something ?

### ISSUE THREAD

**Issue by aiamuzz** [flathub/org.gottcode.FocusWriter#2]
Hi,

I am sorry i just came across your apps after you got added to flathub.

I have installed
Kapow ( which i have certain use for ) 
NovProg and FocusWriter ( I would surely want to write ... but that's an open ended thing ... easier said then done :) )

The application NovProg ... how does it work ... does one have to manually enter the number of words one has written daily ?

I was like shouldn't 'NovProg' & 'Focus Writer' be one application as both are tools for a writer ?

Eg. : 'Kapow' which i love for its simplicity ...

In Kapow i create a Project/Client i am working with ... every time i start the timer the hours of work going into that project is getting counted as separate session.

Similarly can't 'NovProg' & 'FocusWriter' be designed to work in the same manner ... only here the Project will be the Novel/Book being written ... and the start/stop is the writing session ... that way NovProg could count the number of words even recording each writing session, not just just showing graphical data on a day basis but even the time of day basis productivity in the early mornings during bedtimes ... i mean you can record and analyse data in endless forms ... and the same can be shown graphically ?

I am sorry ... if it already works that way ... if so then i haven't figured it out.

But if it does not work that way ... don't you think it would be great if it did ... Something like NovProg as a plugin to FocusWriter ???

just thinking out loud !!!

:)

**Comment by gottcode** [comment]
Yes, NovProg requires you to enter the wordcount manually. It would actually be more complicated than it seems to integrate the two programs, and tracking at what times you write would require tracking more data than is currently tracked in either program. Neither NovProg nor FocusWriter tracks with the same level of detail as Kapow.

Other users have requested a NovProg like graph in FocusWriter before, and I might add one at some point.

**Comment by aiamuzz** [comment]
> Other users have requested a NovProg like graph in FocusWriter before, and I might add one at some point.

I understand ... programming is never easy ... 
Do give us a shout whenever you add such a plugin to FocusWriter 
:)
